# Use the latest Node.js image
FROM node:latest

# Create a directory for the app
WORKDIR /app

# Create a volume to link the source folder with the container's app directory
VOLUME /app

# Start the application
CMD ["bash"]
